### ISSUE TITLE
Can't go to scandinavium

### ISSUE THREAD

**Issue by ltworf** [ltworf/pysttrafik#7]
```
Traceback (most recent call last):
  File "/home/salvo/bin/trip", line 91, in <module>
    main()
  File "/home/salvo/bin/trip", line 79, in main
    dest = get_stop('TO: > ')
  File "/home/salvo/bin/trip", line 46, in get_stop
    stops = vast.location(line)
  File "/home/salvo/dev/pysttrafik/pysttrafik.py", line 140, in location
    return [Stop(i) for i in c]
  File "/home/salvo/dev/pysttrafik/pysttrafik.py", line 577, in __init__
    self.id = d['id']
TypeError: string indices must be integers
```

This happens every time scandinavium is selected as destination.

**Comment by ltworf** [comment]
Well it no longer happens…
